### PR TITLE
Fix lintjs errors and activate it in CI

### PR DESCRIPTION
**Pull request by josojo**
No logical changes, just formatting and activiating CI checks

### CODE REVIEW

**Review by edmundedgar — COMMENTED** [review]
Is this mostly just running the linter and letting it do stuff automatically because I have the unmerged refactoring on the branch `refactorDeploymentScripts` and it's going to be a pita to resolve them so it would be easier to merge them first, or run the linter on them then merge them

**Comment by josojo** [comment]
Hm... quite some things needed manual code changes to resolve the issues.

But feel free to incoroprate the changes into your PR. Then I don't mind.

**Comment by edmundedgar** [comment]
OK, I'll incorporate them.

**Comment by josojo** [comment]
replaced by #175

**Pull request closed without merging**
