### PR TITLE
Basic web infrastructure

### PR DESCRIPTION
**Pull request by edmundedgar**
Adding to git the full static website, plus config files for an HTTPS proxy to the RPC and block explorer services.

RPC would probably have better performance with Nginx or a differently-configured apache but this should get us going for now.

### CODE REVIEW

**Review by josojo — APPROVED** [review]
Looks good. 

I am just wondering whether we should put it into a separate repo. Since there are no direct dependencies, I think it would make sense. 
Wdyt?

**Comment by edmundedgar** [comment]
Yeah, I also wondered which way to go on that. Don't really have a strong opinion. The reason I went on the same-repo side was there will probably be other infrastructure we run that does have dependencies on configuration stuff, and it would be weird to split that up from this.

**Comment by josojo** [comment]
I am in favor of either starting in another repo(a frontend repo), or reorganizing the whole repo with a better top folder structure. 
I kind a like how polygon did it with their backend, frontend, smartcontract and zkstuff split.

**Comment by edmundedgar** [comment]
This should go in `RealityETH/server-config`, right?

**Comment by edmundedgar** [comment]
Closing this because we put it in `server-config` instead

**Pull request closed without merging**
