### PR TITLE
makes requestToArbitrate permissionless after a time period

### PR DESCRIPTION
**Pull request by josojo**
closes: https://github.com/RealityETH/subjectivocracy/issues/199 and adds some test

### CODE REVIEW

**Comment by edmundedgar** [comment]
If I've understood this right it makes it permissionless to retry the fork, so anyone can do it after a deadline, but cancelling arbitration can only be done by the payer. 

Is there any risk that retrying the fork will fail, eg because the fee has gone up? If so it might be safer to instead make it permissionless to cancel arbitration, or to provide a permissionless path for both.

**Comment by josojo** [comment]
>If I've understood this right it makes it permissionless to retry the fork, so anyone can do it after a deadline, but cancelling arbitration can still only be done by the payer.

Hm... if this can really fail, then a malicious payer could just reinitated the arbitration again and again and thereby also block the question resolution for a long time. Currently, this can only happen, if the security council bumps the arbitration fees, right? let me think more about it

**Comment by edmundedgar** [comment]
This is probably not this PR's fault but what happens if you request arbitration but then the fork fee goes up before you can call `requestActivateFork`? It looks to me like you can't get make the fork happen because the fee you paid is too low, but you also can't cancel because you never get into the failed state.

**Comment by edmundedgar** [comment]
It seems bad that anyone can call `storeInformation` and overwrite any question?

**Comment by josojo** [comment]
> It seems bad that anyone can call `storeInformation` and overwrite any question?

the questionId has the msg.sender in it. Hence, people how just call it store some information for a questionId that is not relevant:
```
bytes32 question_id = keccak256(
            abi.encodePacked(
                contentHash,
                address(this),
                timeout,
                minBond,
                address(realitio),
                msg.sender,
                nonce
            )
        );
        ```

**Comment by josojo** [comment]
> This is probably not this PR's fault but what happens if you request arbitration but then the fork fee goes up before you can call `requestActivateFork`? It looks to me like you can't get make the fork happen because the fee you paid is too low, but you also can't cancel because you never get into the failed state.

Nice catch. I think we should implement a "top up" function for a request and a function that allows to cancel the arbitration without failure, if paid<arbitrationFee

**Review by edmundedgar — APPROVED** [review]
Approving this, the code seems good. On balance I know feel like with this and the previous retrying thing we've ended up adding more complexity than we should have to retry the fork when always cancelling arbitration and pushing it through again would have worked fine, as it's quite an unusual case and not much of a speed-up. But I don't feel strongly about it.

**Comment by josojo** [comment]
>
Approving this, the code seems good. On balance I now feel like with this and the previous retrying thing we've ended up adding more complexity than we should have to retry the fork when always cancelling arbitration and pushing it through again would have worked fine, as it's quite an unusual case and not much of a speed-up. But I don't feel strongly about it.

I also hate complexity. 
The main reason for fast resubmission are:
- we don't wanna have the additional time delay again (Probably one could fix this, by marking questionsIds that have been asked before)
- If funds were crowdfunded, a resubmission logic would be required in the crowdfund contract. This would shift the complexity more to the edges and increase the gas costs. (Probably sending complexity to the "edges" is better.).
- if a fork would have to be reinitiated via an L1 tx, its much easier, if the tx is easier to build (but maybe this is just an engineering challenge that can easily be solved with the right tooling)

=> I am concluding: Let me try to rewrite it without resubmission logic and we can evaluate it one more time.

**Comment by edmundedgar** [comment]
> If funds were crowdfunded, a resubmission logic would be required in the crowdfund contract. This would shift the complexity more to the edges and increase the gas costs. (Probably sending complexity to the "edges" is better.).

I think you need this logic even if you have fork-retry because you have to cover the case where the price goes up. Plus if you have the functions that the payer is supposed to call (cancel or retry) you need logic to cover doing that.

**Comment by edmundedgar** [comment]
> we don't wanna have the additional time delay again (Probably one could fix this, by marking questionsIds that have been asked before)

That seems simpler, doesn't it? Mark the time when the question id is first created, then never clear it.

**Pull request closed without merging**
